# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 4.0.3.{build}

# branches to build
branches:
  # whitelist
  only:
    - default

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "4.0.3.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

build:
  project: Troschuetz.Random.sln      # path to Visual Studio solution or project

# build Configuration, i.e. Debug, Release, etc.
configuration: Debug
  
#---------------------------------#
#          web settings           #
#---------------------------------#

# crontab: 0 21 * * *