//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Troschuetz.Random {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Troschuetz.Random.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List must not be empty..
        /// </summary>
        internal static string EmptyList {
            get {
                return ResourceManager.GetString("EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given parameter (or parameters) are not valid..
        /// </summary>
        internal static string InvalidParams {
            get {
                return ResourceManager.GetString("InvalidParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxValue should be greater than or equal to minValue..
        /// </summary>
        internal static string MinValueGreaterThanMaxValue {
            get {
                return ResourceManager.GetString("MinValueGreaterThanMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxValue must be greater than or equal to zero..
        /// </summary>
        internal static string NegativeMaxValue {
            get {
                return ResourceManager.GetString("NegativeMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer must not be undefined..
        /// </summary>
        internal static string NullBuffer {
            get {
                return ResourceManager.GetString("NullBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution must not be undefined..
        /// </summary>
        internal static string NullDistribution {
            get {
                return ResourceManager.GetString("NullDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator must not be undefined..
        /// </summary>
        internal static string NullGenerator {
            get {
                return ResourceManager.GetString("NullGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List must not be undefined..
        /// </summary>
        internal static string NullList {
            get {
                return ResourceManager.GetString("NullList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weights collection must not be undefined..
        /// </summary>
        internal static string NullWeights {
            get {
                return ResourceManager.GetString("NullWeights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean is undefined for given distribution..
        /// </summary>
        internal static string UndefinedMean {
            get {
                return ResourceManager.GetString("UndefinedMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean is undefined for given distribution under given parameters..
        /// </summary>
        internal static string UndefinedMeanForParams {
            get {
                return ResourceManager.GetString("UndefinedMeanForParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median is undefined for given distribution..
        /// </summary>
        internal static string UndefinedMedian {
            get {
                return ResourceManager.GetString("UndefinedMedian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode is undefined for given distribution..
        /// </summary>
        internal static string UndefinedMode {
            get {
                return ResourceManager.GetString("UndefinedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode is undefined for given distribution under given parameters..
        /// </summary>
        internal static string UndefinedModeForParams {
            get {
                return ResourceManager.GetString("UndefinedModeForParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variance is undefined for given distribution..
        /// </summary>
        internal static string UndefinedVariance {
            get {
                return ResourceManager.GetString("UndefinedVariance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variance is undefined for given distribution under given parameters..
        /// </summary>
        internal static string UndefinedVarianceForParams {
            get {
                return ResourceManager.GetString("UndefinedVarianceForParams", resourceCulture);
            }
        }
    }
}
